import { z } from "zod";

export const studentSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  fatherName: z.string(),
  motherName: z.string(),
  dateOfBirth: z.string(),
  gender: z.enum(["MALE", "FEMALE", "OTHER"]),
  class: z.enum([
    "FIRST",
    "SECOND",
    "THIRD",
    "FOURTH",
    "FIFTH",
    "SIXTH",
    "SEVENTH",
    "EIGHTH",
    "NINTH",
    "TENTH",
    "ELEVENTH",
    "TWELFTH",
  ]),
  section: z.enum(["A", "B", "C", "D"]),
  relegion: z.enum([
    "HINDU",
    "MUSLIM",
    "CHRISTIAN",
    "SIKH",
    "BUDDHIST",
    "JAIN",
    "OTHER",
  ]),
  address: z.string(),
  phoneNumber: z.string(),
  city: z.string(),
  state: z.string(),
  zipCode: z.string(),
  country: z.string(),
  rollNumber: z.number().optional(),
  bloodGroup: z.string().optional(),
  photo: z.string().optional(),
  email: z.string().email().optional(),
  status: z.enum(["ACTIVE", "INACTIVE", "SUSPENDED"]).optional(),
});
